apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  'redcross'_customers:
    app: 'redcross'_customer
spec:
  selector:
    matchLabels:
      app: 'redcross'_customer
  template:
    metadata:
      'redcross'_customers: # 'redcross'_customers to select/identify the deployment
        app: 'redcross'_customer
    spec:     # pod spec
      containers: 
      - name: 'redcross'_customer
        ports:
        - containerPort: 10
          $patch: delete
        - containerPort: 80  
          
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  'redcross'_customers:
    app: 'redcross'_customer
spec:
  selector:
    app: 'redcross'_customer
  ports:
    - port: 8080
      $patch: delete
      targetPort: 10
      $patch: delete
    - port: 8081
      targetPort: 80  


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
spec:
  hosts:
  #   - abc.sreyo.in
  #     $patch: delete
    # - def.sreyo.in  
    - redcross.sreyo.in
  http:
    - route:
        - destination:
            # host: frontend-service.default.svc.cluster.local
            # $patch: delete
            # host: test-frontend-service.default.svc.cluster.local
            host: redcross-frontend-service.default.svc.cluster.local
            port:
              # number: 8081  
              # $patch: delete 
              number: 8081
