apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: hi-frontend
spec:
  selector:
    matchLabels:
      app: hi-frontend
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: hi-frontend
    spec:     # pod spec
      containers: 
      - name: hi-frontend
        ports:
        - containerPort: 10
          $patch: delete
        - containerPort: 1339  
          
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: hi-frontend
spec:
  selector:
    app: hi-frontend
  ports:
    - port: 8080
      $patch: delete
      targetPort: 10
      $patch: delete
    - port: 1339
      targetPort: 1339  


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
spec:
  hosts:
  #   - abc.sreyo.in
  #     $patch: delete
    # - def.sreyo.in  
    - ghi.sreyo.in
  http:
    - route:
        - destination:
            # host: frontend-service.default.svc.cluster.local
            # $patch: delete
            # host: test-frontend-service.default.svc.cluster.local
            host: hi-frontend-service.default.svc.cluster.local
            port:
              # number: 8081  
              # $patch: delete 
              number: 1339
